version: "3"

services:
  app:
    image: gmazzitelli/cygno-tape:v1.0.5-cygno
    container_name: taper
    stdin_open: true # docker run -i
    tty: true        # docker run ≈-t
#    environment:
#      MYSQL_IP: ${MYSQL_IP}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ${PWD}/script:/root/script
      - /home/mazzitel/docker/taper:/root/data

